name = "NetworkDesignOptimization"
uuid = "e92b3169-8dd3-4529-9d46-f74323416df7"
authors = ["LÃ©o Baty and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.1"
Dates = "1.11.0"
Distances = "0.10.12"
DocStringExtensions = "0.9.5"
GLMakie = "0.13.6"
Graphs = "1.13.1"
MetaGraphsNext = "0.7.4"
MultivariateStats = "0.10.3"
Plots = "1.40.19"
SimpleWeightedGraphs = "1.5.0"
Tyler = "0.2.4"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
