name = "NetworkDesignOptimization"
uuid = "e92b3169-8dd3-4529-9d46-f74323416df7"
version = "0.0.1"
authors = ["LÃ©o Baty and contributors"]

[workspace]
projects = ["docs", "test", "scripts"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
WrappedUnions = "325db55a-9c6c-5b90-b1a2-ec87e7a38c44"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.1"
Dates = "1.11.0"
DocStringExtensions = "0.9.5"
Graphs = "1.13.1"
MetaGraphsNext = "0.7.4"
WrappedUnions = "0.3.3"
julia = "1.11"
