[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
TransportationPlanningOptimization = "e92b3169-8dd3-4529-9d46-f74323416df7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
TransportationPlanningOptimization = {path = ".."}
